layout_spectrum: 0.6002401953604588
typography_spectrum: 0.313274398556182
color:
  brandStrength: 0.20661424468363646
  lightness: 0.5643221233887507
  saturation: 0.7529711976905565
  rhythmicContrast: 0.2610051128920168
  brandColors:
    - '#2C3E50'
    - '#E74C3C'
    - '#ECF0F1'
    - '#3498DB'
    - '#2980B9'
github: true
analytics:
  google: UA-77405872-2
author:
  name: Martin Stangl
  email: martin.stangl@theblacklion.net
  url: 'http://www.theblacklion.net'
name: SUVs & Crossovers
url: 'http://suv2017.theblacklion.net'
colors:
  brandColors:
    - 'hsl(0,0%,100%)'
    - 'hsl(0,0%,80%)'
    - 'hsl(0,0%,60%)'
    - 'hsl(0,0%,30%)'
    - 'hsl(0,0%,20%)'
navigation:
  - name: Seat Ateca
    id: c1b33e14-2979-4fcf-8648-68b65beea633
    type: content
  - name: Mitsubishi Outlander
    id: 9f5b9057-bcbf-40fa-a2ec-07a0c82d8231
    type: content
  - name: Honda CR-V
    id: f8e0706e-143e-48cb-95e6-3e5eef2cf12f
    type: content
  - name: Skoda Kodiaq
    id: 92c91c35-98d7-4781-b5b0-b089f5c78873
    type: content
  - name: Nissan X-Trail
    id: b7519473-016f-4aab-9ac9-1984127199b3
    type: content
  - name: VW Tiguan
    id: a1896816-70cf-4987-90fc-5893e94c16f3
    type: content
  - name: Peugeot 5008
    id: 3ce3105e-700e-4cec-a325-32487d530813
    type: content
title: Auswahlliste neues Auto
content: []
description: 'aus SUV-/Crossover-Neuwagen in Österreich, Stand April 2017'
